# Generated by Django 4.0.6 on 2022-08-27 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='created',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='modified',
        ),
        migrations.AddField(
            model_name='user',
            name='mail',
            field=models.EmailField(blank=True, max_length=100, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=15, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telefono',
            field=models.IntegerField(),
        ),
    ]
