# Generated by Django 4.0.6 on 2022-08-31 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tipo',
            field=models.IntegerField(choices=[(0, 'admin'), (1, 'superusuario')], null=True),
        ),
    ]
