# Generated by Django 4.0.6 on 2022-08-27 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_remove_user_created_remove_user_email_and_more'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='created',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='modified',
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Proyecto_Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('proyecto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.proyecto')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.user')),
            ],
        ),
    ]
